# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f92cbbfe723fd6ed1156a54ac16a50c2864858a59681f2f550d0ba6247746e4a07ea7c5b2d7b37eaaf1e9d0a52f85bff5454cbc53aa288d3e02072626021ee

test:
  secret_key_base: a6332b0a70b4b8cc8372b096e88578f6302f5c7a871baee4330c44f180cd968756a6e9a7f8feac478dc2dd4b9fb2f35a6d72773f53571b07d7749ae536467b8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
